webtalk_init -webtalk_dir F:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_test/NDVI_test.sim/sim_1/behav/xsim/xsim.dir/tb_NDVI_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 28 16:11:30 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211751307_0_0_242" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "074f79a8-6b98-44bd-afa8-57f8cb20eb89" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "20918d76542d4bca9badf2197e5c6bc0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.36_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8168_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1610639962 -regid "211751307_0_0_242" -xml F:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_test/NDVI_test.sim/sim_1/behav/xsim/xsim.dir/tb_NDVI_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_test/NDVI_test.sim/sim_1/behav/xsim/xsim.dir/tb_NDVI_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_test/NDVI_test.sim/sim_1/behav/xsim/xsim.dir/tb_NDVI_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
