# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/UOM/Semester7/FYP/NDVI_Camera/PickTea/HOME2_C1/VIVADO/lab2_home/lab2_home.srcs/sources_1/ip/AXI4Stream_RS232_0/AXI4Stream_RS232_0.xci
# IP: The module: 'AXI4Stream_RS232_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/UOM/Semester7/FYP/NDVI_Camera/PickTea/HOME2_C1/VIVADO/lab2_home/lab2_home.srcs/sources_1/ip/AXI4Stream_RS232_0/AXI4Stream_RS232_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI4Stream_RS232_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/UOM/Semester7/FYP/NDVI_Camera/PickTea/HOME2_C1/VIVADO/lab2_home/lab2_home.srcs/sources_1/ip/AXI4Stream_RS232_0/AXI4Stream_RS232_0.xci
# IP: The module: 'AXI4Stream_RS232_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/UOM/Semester7/FYP/NDVI_Camera/PickTea/HOME2_C1/VIVADO/lab2_home/lab2_home.srcs/sources_1/ip/AXI4Stream_RS232_0/AXI4Stream_RS232_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI4Stream_RS232_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
