# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_Image_1.2/NDVI_Image_1.2.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base.xci
# IP: The module: 'clk_wiz_base' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_Image_1.2/NDVI_Image_1.2.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_Image_1.2/NDVI_Image_1.2.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_Image_1.2/NDVI_Image_1.2.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_Image_1.2/NDVI_Image_1.2.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base.xci
# IP: The module: 'clk_wiz_base' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_Image_1.2/NDVI_Image_1.2.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_Image_1.2/NDVI_Image_1.2.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/UOM/Semester7/FYP/NDVI_Camera/PickTea/NDVI_Image_1.2/NDVI_Image_1.2.srcs/sources_1/ip/clk_wiz_base/clk_wiz_base_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_base'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
